# Generated by Django 3.2.6 on 2021-08-15 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20210815_2146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['name', 'country']},
        ),
        migrations.RemoveField(
            model_name='author',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='book',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='author',
            name='name',
            field=models.CharField(default='Unknown', max_length=100, verbose_name='Full Name'),
        ),
        migrations.AddField(
            model_name='book',
            name='pub_year',
            field=models.CharField(default='2021', max_length=50, verbose_name='Year'),
        ),
    ]
