# Generated by Django 3.2.6 on 2021-08-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20210816_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publsiher',
            new_name='publisher',
        ),
        migrations.RemoveField(
            model_name='book',
            name='pub_year',
        ),
        migrations.AddField(
            model_name='book',
            name='pub_date',
            field=models.CharField(default='2021', max_length=50, verbose_name='Published'),
        ),
    ]
